export * from './enrollStudentToSubject.controller'
export * from './getAllSubject.controller'
export * from './getClassmateNameInSameSubjects.controller'
export * from './loginStudent.controller'
export * from './registerStudent.controller'
